// ═══════════════════════════════════════════════════════════════════════════
// FINPATHIA · pdfSectionExport.js — PDF por módulo (Patrimonio, Ingresos,
// Gastos, Deudas)
//
// PROPÓSITO:
//   Genera un PDF legible de cada sección, para imprimir, archivar o mandar
//   al contador / al banco / a la familia.
//
// POR QUÉ NO ES UN CLON DE excelExport.js:
//   El Excel es el volcado completo: 10-12 columnas, todos los campos, para
//   que el que recibe pueda filtrar y recalcular. El PDF es un documento que
//   alguien lee. Meter 12 columnas en una hoja Letter da una tabla de 7pt
//   ilegible. Por eso acá cada sección lleva las columnas que sostienen la
//   lectura, más un resumen arriba y un desglose por categoría abajo.
//   Los dos exports conviven: Excel para trabajar los datos, PDF para leerlos.
//
// CONSISTENCIA CON excelExport.js (deliberada, no accidental):
//   - Mismo filtro sim !== false en las 4 secciones
//   - Mismos campos de origen (i.mensual, g.m, d.mt, i.va…)
//   - Mismos totales, para que un Excel y un PDF de la misma fecha no puedan
//     contradecirse. Si cambia el criterio en un lado, cambia en los dos.
//
// TÉCNICA:
//   jsPDF + jspdf-autotable con import dinámico, igual que pdfExport.js: son
//   la mayor carga muerta del bundle y solo debe bajarlas quien exporta.
// ═══════════════════════════════════════════════════════════════════════════

// ── Jurisdicción ────────────────────────────────────────────────────────────
// 01-sep-2026: los módulos US no tenían NINGÚN export -- ni PDF ni Excel.
// En vez de duplicar este archivo se agrega un modo inglés: mismos cálculos y
// misma estructura, solo cambian etiquetas y formato de número. Duplicar
// habría significado que cada corrección futura hubiera que hacerla dos veces,
// y es exactamente así como los dos lados terminan divergiendo en silencio.
const L = {
  es: {
    loc: "es-CO", cur: "$",
    patrimonio: "Patrimonio", ingresos: "Ingresos", gastos: "Gastos", deudas: "Deudas",
    activo: "Activo", tipo: "Tipo", propietario: "Propietario",
    valorCompra: "Valor compra", valorActual: "Valor actual", ganancia: "Ganancia",
    activos: "Activos", total: "TOTAL", concentracion: "Concentración por tipo",
    nActivos: "# Activos", pctPortafolio: "% del portafolio",
    fuente: "Fuente", categoria: "Categoría DIAN", propTipo: "Tipo",
    mensual: "Mensual", anual: "Anual", fuentes: "Fuentes",
    totalMensual: "Total mensual", totalAnual: "Total anual",
    nIngresos: "# Ingresos", pctTotal: "% del total",
    concepto: "Concepto", fijo: "Fijo", variable: "Variable",
    items: "Ítems", fijos: "Fijos", variables: "Variables", nItems: "# Ítems",
    deuda: "Deuda", vinculada: "Vinculada a", saldo: "Saldo", cuotaMes: "Cuota mes",
    tasa: "Tasa", meses: "Meses", saldoTotal: "Saldo total",
    cuotaMensual: "Cuota mensual", tasaProm: "Tasa promedio",
    ordenPago: "Orden sugerido de pago (mayor tasa primero)",
    costoIntereses: "Costo anual en intereses",
    tagline: "Tu family office",
    sinItems: (q) => `No hay ${q} activos para exportar. Prendé al menos uno con el toggle ✅.`,
    nota: "Documento generado por FINPATHIA. Incluye únicamente los ítems activos (los apagados con el toggle quedan fuera de las tablas y de los totales). Cifras de referencia, no constituyen asesoría fiscal ni estados financieros auditados.",
  },
  en: {
    loc: "en-US", cur: "$",
    patrimonio: "Net Worth", ingresos: "Income", gastos: "Expenses", deudas: "Debts",
    activo: "Asset", tipo: "Type", propietario: "Owner",
    valorCompra: "Cost basis", valorActual: "Current value", ganancia: "Gain",
    activos: "Assets", total: "TOTAL", concentracion: "Concentration by type",
    nActivos: "# Assets", pctPortafolio: "% of portfolio",
    fuente: "Source", categoria: "Category", propTipo: "Type",
    mensual: "Monthly", anual: "Annual", fuentes: "Sources",
    totalMensual: "Monthly total", totalAnual: "Annual total",
    nIngresos: "# Items", pctTotal: "% of total",
    concepto: "Item", fijo: "Fixed", variable: "Variable",
    items: "Items", fijos: "Fixed", variables: "Variable", nItems: "# Items",
    deuda: "Debt", vinculada: "Linked to", saldo: "Balance", cuotaMes: "Monthly payment",
    tasa: "Rate", meses: "Months", saldoTotal: "Total balance",
    cuotaMensual: "Monthly payment", tasaProm: "Average rate",
    ordenPago: "Suggested payoff order (highest rate first)",
    costoIntereses: "Annual interest cost",
    tagline: "Your family office",
    sinItems: (q) => `No active ${q} to export. Turn at least one on with the toggle ✅.`,
    nota: "Generated by FINPATHIA. Includes only active items (anything switched off is excluded from the tables and the totals). Reference figures only; not tax advice nor audited financial statements.",
  },
};

// ── Helpers de formato ──────────────────────────────────────────────────────
// El signo va delante del $, no entre el $ y el número: "-$9.000.000" y no
// "$-9.000.000", que es como lo escribe toLocaleString y se lee mal en una
// columna de pérdidas.
let LOC = "es-CO";   // se fija al inicio de cada export segun jurisdiccion
const fm = (v) => {
  const n = Math.round(Number(v) || 0);
  return (n < 0 ? "-$" : "$") + Math.abs(n).toLocaleString(LOC);
};
const pct = (v) => (Number(v) || 0).toFixed(1) + "%";

const fmDate = () =>
  new Date().toLocaleDateString(LOC, { year: "numeric", month: "long", day: "numeric" });

const buildFilename = (modulo) =>
  `FINPATHIA_${String(modulo).replace(/ /g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`;

// 12-ago-2026: los exportadores sumaban dólares y pesos en el mismo total.
// Un activo cargado en USD entraba con su número crudo a un total en pesos,
// así que el patrimonio exportado no coincidía con el de la pantalla y era
// ~4.200 veces más chico en esa fila. Toda cifra que entra a una tabla o a un
// total pasa ahora por esta conversión. La regla es la misma que usa el resto
// de la app (flowHelpers): sin campo moneda se asume COP, por retrocompat.
const aCOP = (monto, item, trm) =>
  (Number(monto) || 0) * (item?.moneda === "USD" ? (trm || 4200) : 1);

const ownerName = (ownerId, owners) => {
  if (!ownerId) return "";
  const o = (owners || []).find((x) => x.id === ownerId);
  return o ? o.name || o.n || "" : "";
};

// Paleta alineada con pdfExport.js para que los PDFs de FINPATHIA se vean
// como una familia y no como cuatro documentos sueltos.
const PURPLE = [124, 58, 237];
const INK = [20, 20, 24];
const GRAY = [120, 120, 130];
const LINE = [220, 220, 225];

/**
 * Header + footer comunes. Devuelve la Y donde puede empezar el contenido.
 */
let TAGLINE = "Tu family office";

function chrome(doc, { titulo, subtitulo }) {
  const W = doc.internal.pageSize.getWidth();
  const M = 14;

  doc.setFillColor(...PURPLE);
  doc.rect(0, 0, W, 8, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...INK);
  doc.text("FINPATHIA", M, 20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(TAGLINE, M, 25);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...INK);
  doc.text(titulo, W - M, 20, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(subtitulo || fmDate(), W - M, 25, { align: "right" });

  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.3);
  doc.line(M, 30, W - M, 30);

  return 38;
}

/**
 * Bloque de cifras clave. Hasta 4 por fila para que no se apelmacen.
 */
function resumen(doc, y, stats) {
  const W = doc.internal.pageSize.getWidth();
  const M = 14;
  const cols = Math.min(stats.length, 4);
  const cw = (W - M * 2) / cols;

  stats.forEach((s, i) => {
    const x = M + cw * (i % cols);
    const row = Math.floor(i / cols);
    const yy = y + row * 18;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...GRAY);
    doc.text(String(s.label).toUpperCase(), x, yy);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...(s.color || INK));
    doc.text(String(s.value), x, yy + 7);
  });

  return y + Math.ceil(stats.length / cols) * 18 + 4;
}

/**
 * Pie de página con numeración y la aclaración de qué incluye el documento.
 * Se dibuja al final, cuando ya se sabe cuántas páginas hay.
 */
function footer(doc, nota) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 14;
  const total = doc.internal.getNumberOfPages();

  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.3);
    doc.line(M, H - 16, W - M, H - 16);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(nota, M, H - 11, { maxWidth: W - M * 2 - 25 });
    doc.text(`${p} / ${total}`, W - M, H - 11, { align: "right" });
  }
}

/**
 * Envoltorio: carga las libs, arma el doc, dibuja y descarga.
 */
async function build(filename, drawFn, nota) {
  const [jm, am] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);

  // jspdf expone el constructor distinto según cómo se resuelva el módulo:
  // bundleado por Vite llega como default, en Node ESM el default es el
  // namespace CJS y el constructor cuelga de .jsPDF. Probamos las tres formas
  // en vez de asumir una, así el mismo archivo corre en el navegador y en los
  // tests. Igual para autotable.
  const jsPDF = jm.jsPDF || (jm.default && jm.default.jsPDF) || jm.default;
  const autoTable = (am.default && am.default.default) || am.default || am.autoTable;

  const doc = new jsPDF({ unit: "mm", format: "letter" });
  drawFn(doc, autoTable);
  footer(doc, nota);
  doc.save(filename);
}

// Estilo de tabla único para las 4 secciones.
const tableStyle = {
  theme: "striped",
  headStyles: { fillColor: PURPLE, textColor: 255, fontSize: 8.5, fontStyle: "bold" },
  bodyStyles: { fontSize: 8.5, textColor: INK },
  alternateRowStyles: { fillColor: [248, 248, 250] },
  footStyles: { fillColor: [238, 238, 242], textColor: INK, fontStyle: "bold", fontSize: 8.5 },
  margin: { left: 14, right: 14, bottom: 22 },
};


// ═══════════════════════════════════════════════════════════════════════════
// 1. PATRIMONIO
// ═══════════════════════════════════════════════════════════════════════════
export async function exportPatrimonioPDF(inversiones, owners, trm, en = false) {
  const t = en ? L.en : L.es; LOC = t.loc; TAGLINE = t.tagline;
  const items = (inversiones || []).filter((i) => i.sim !== false);
  if (items.length === 0) {
    alert(t.sinItems(en ? "assets" : "activos"));
    return;
  }

  const totalVa = items.reduce((s, i) => s + aCOP(i.va, i, trm), 0);
  const totalVc = items.reduce((s, i) => s + aCOP(i.vc, i, trm), 0);
  const gain = totalVa - totalVc;
  const gainPct = totalVc > 0 ? ((totalVa / totalVc) - 1) * 100 : 0;

  await build(buildFilename(t.patrimonio), (doc, autoTable) => {
    let y = chrome(doc, { titulo: t.patrimonio });

    y = resumen(doc, y, [
      { label: t.activos, value: String(items.length) },
      { label: t.valorCompra, value: fm(totalVc) },
      { label: t.valorActual, value: fm(totalVa) },
      {
        label: t.ganancia,
        value: `${fm(gain)} (${gainPct >= 0 ? "+" : ""}${gainPct.toFixed(1)}%)`,
        color: gain >= 0 ? [22, 163, 74] : [220, 38, 38],
      },
    ]);

    autoTable(doc, {
      ...tableStyle,
      startY: y,
      head: [[t.activo, t.tipo, t.propietario, t.valorCompra, t.valorActual, t.ganancia, "%"]],
      body: items
        .slice()
        .sort((a, b) => aCOP(b.va, b, trm) - aCOP(a.va, a, trm))
        .map((i) => {
          const vc = aCOP(i.vc, i, trm);
          const va = aCOP(i.va, i, trm);
          const g = va - vc;
          return [
            i.nombre || i.n || "",
            i.tp || i.tipo || "Otro",
            ownerName(i.ownerId, owners),
            fm(vc),
            fm(va),
            fm(g),
            vc > 0 ? `${g >= 0 ? "+" : ""}${(((va / vc) - 1) * 100).toFixed(1)}%` : "—",
          ];
        }),
      foot: [[t.total, "", "", fm(totalVc), fm(totalVa), fm(gain), `${gainPct >= 0 ? "+" : ""}${gainPct.toFixed(1)}%`]],
      columnStyles: {
        3: { halign: "right" }, 4: { halign: "right" },
        5: { halign: "right" }, 6: { halign: "right" },
      },
    });

    // Desglose por tipo: responde "en qué está concentrado mi patrimonio",
    // que es la pregunta real detrás de exportar esta sección.
    const porTipo = {};
    items.forEach((i) => {
      const tp = i.tp || i.tipo || "Otro";
      if (!porTipo[tp]) porTipo[tp] = { count: 0, va: 0 };
      porTipo[tp].count += 1;
      porTipo[tp].va += aCOP(i.va, i, trm);
    });

    autoTable(doc, {
      ...tableStyle,
      startY: doc.lastAutoTable.finalY + 10,
      head: [[t.concentracion, t.nActivos, t.valorActual, t.pctPortafolio]],
      body: Object.entries(porTipo)
        .sort((a, b) => b[1].va - a[1].va)
        .map(([tp, d]) => [
          tp,
          String(d.count),
          fm(d.va),
          totalVa > 0 ? pct((d.va / totalVa) * 100) : "0.0%",
        ]),
      columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" } },
    });
  }, t.nota);
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. INGRESOS
// ═══════════════════════════════════════════════════════════════════════════
export async function exportIngresosPDF(ingresos, owners, trm, en = false) {
  const t = en ? L.en : L.es; LOC = t.loc; TAGLINE = t.tagline;
  const items = (ingresos || []).filter((i) => i.sim !== false);
  if (items.length === 0) {
    alert(t.sinItems(en ? "income items" : "ingresos"));
    return;
  }

  const mens = (i) => aCOP(i.mensual, i, trm);
  const totalMes = items.reduce((s, i) => s + mens(i), 0);

  await build(buildFilename(t.ingresos), (doc, autoTable) => {
    let y = chrome(doc, { titulo: t.ingresos });

    y = resumen(doc, y, [
      { label: t.fuentes, value: String(items.length) },
      { label: t.totalMensual, value: fm(totalMes), color: [22, 163, 74] },
      { label: t.totalAnual, value: fm(totalMes * 12), color: [22, 163, 74] },
    ]);

    autoTable(doc, {
      ...tableStyle,
      startY: y,
      head: [[t.fuente, t.categoria, t.propTipo, t.propietario, t.mensual, t.anual]],
      body: items
        .slice()
        .sort((a, b) => mens(b) - mens(a))
        .map((i) => [
          i.nombre || "",
          i.categoria || "",
          i.tipo || "fijo",
          ownerName(i.ownerId, owners),
          fm(mens(i)),
          fm(mens(i) * 12),
        ]),
      foot: [[t.total, "", "", "", fm(totalMes), fm(totalMes * 12)]],
      columnStyles: { 4: { halign: "right" }, 5: { halign: "right" } },
    });

    const porCat = {};
    items.forEach((i) => {
      const cat = i.categoria || "Sin categoría";
      if (!porCat[cat]) porCat[cat] = { count: 0, mensual: 0 };
      porCat[cat].count += 1;
      porCat[cat].mensual += mens(i);
    });

    autoTable(doc, {
      ...tableStyle,
      startY: doc.lastAutoTable.finalY + 10,
      head: [[t.categoria, t.nIngresos, t.mensual, t.anual, t.pctTotal]],
      body: Object.entries(porCat)
        .sort((a, b) => b[1].mensual - a[1].mensual)
        .map(([cat, d]) => [
          cat,
          String(d.count),
          fm(d.mensual),
          fm(d.mensual * 12),
          totalMes > 0 ? pct((d.mensual / totalMes) * 100) : "0.0%",
        ]),
      columnStyles: {
        1: { halign: "right" }, 2: { halign: "right" },
        3: { halign: "right" }, 4: { halign: "right" },
      },
    });
  }, t.nota);
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. GASTOS
// ═══════════════════════════════════════════════════════════════════════════
export async function exportGastosPDF(gastos, trm, en = false) {
  const t = en ? L.en : L.es; LOC = t.loc; TAGLINE = t.tagline;
  // gastos llega como objeto { categoria: [items] }, igual que en Excel.
  const flat = [];
  Object.entries(gastos || {}).forEach(([cat, items]) => {
    (items || [])
      .filter((g) => g.sim !== false)
      .forEach((g) => {
        flat.push({
          categoria: cat,
          concepto: g.c || "",
          monto: aCOP(g.m, g, trm),
          tipo: g.t === "f" ? t.fijo : t.variable,
        });
      });
  });

  if (flat.length === 0) {
    alert(t.sinItems(en ? "expenses" : "gastos"));
    return;
  }

  const totalMes = flat.reduce((s, g) => s + g.monto, 0);
  const fijos = flat.filter((g) => g.tipo === t.fijo).reduce((s, g) => s + g.monto, 0);
  const variables = totalMes - fijos;

  await build(buildFilename(t.gastos), (doc, autoTable) => {
    let y = chrome(doc, { titulo: t.gastos });

    // Fijos vs variables va arriba a propósito: es el dato que decide cuánto
    // de tu gasto podés mover si necesitás ajustar.
    y = resumen(doc, y, [
      { label: t.items, value: String(flat.length) },
      { label: t.totalMensual, value: fm(totalMes), color: [220, 38, 38] },
      { label: t.fijos, value: `${fm(fijos)} (${totalMes > 0 ? pct((fijos / totalMes) * 100) : "0.0%"})` },
      { label: t.variables, value: `${fm(variables)} (${totalMes > 0 ? pct((variables / totalMes) * 100) : "0.0%"})` },
    ]);

    autoTable(doc, {
      ...tableStyle,
      startY: y,
      head: [[t.categoria, t.concepto, t.propTipo, t.mensual, t.anual]],
      body: flat
        .slice()
        .sort((a, b) => b.monto - a.monto)
        .map((g) => [g.categoria, g.concepto, g.tipo, fm(g.monto), fm(g.monto * 12)]),
      foot: [[t.total, "", "", fm(totalMes), fm(totalMes * 12)]],
      columnStyles: { 3: { halign: "right" }, 4: { halign: "right" } },
    });

    const porCat = {};
    flat.forEach((g) => {
      if (!porCat[g.categoria]) porCat[g.categoria] = { count: 0, fijos: 0, variables: 0 };
      porCat[g.categoria].count += 1;
      if (g.tipo === t.fijo) porCat[g.categoria].fijos += g.monto;
      else porCat[g.categoria].variables += g.monto;
    });

    autoTable(doc, {
      ...tableStyle,
      startY: doc.lastAutoTable.finalY + 10,
      head: [[t.categoria, t.nItems, t.fijos, t.variables, t.mensual, t.pctTotal]],
      body: Object.entries(porCat)
        .map(([cat, d]) => ({ cat, ...d, total: d.fijos + d.variables }))
        .sort((a, b) => b.total - a.total)
        .map((d) => [
          d.cat,
          String(d.count),
          fm(d.fijos),
          fm(d.variables),
          fm(d.total),
          totalMes > 0 ? pct((d.total / totalMes) * 100) : "0.0%",
        ]),
      columnStyles: {
        1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" },
        4: { halign: "right" }, 5: { halign: "right" },
      },
    });
  }, t.nota);
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. DEUDAS
// ═══════════════════════════════════════════════════════════════════════════
export async function exportDeudasPDF(deudas, inversiones, owners, trm, en = false) {
  const t = en ? L.en : L.es; LOC = t.loc; TAGLINE = t.tagline;
  // Mismo filtro que el Excel: además de sim !== false, exige saldo > 0.
  // Una deuda saldada no es una deuda.
  const items = (deudas || []).filter((d) => d.sim !== false && (d.mt || 0) > 0);
  if (items.length === 0) {
    alert(t.sinItems(en ? "debts" : "deudas"));
    return;
  }

  const invName = (invId) => {
    if (!invId) return "";
    const inv = (inversiones || []).find((x) => x.id === invId);
    return inv ? inv.nombre || inv.n || "" : "";
  };

  const saldo = (d) => aCOP(d.mt, d, trm);
  const cuota = (d) => aCOP(d.pg, d, trm);
  const totalSaldo = items.reduce((s, d) => s + saldo(d), 0);
  const totalCuota = items.reduce((s, d) => s + cuota(d), 0);
  // Tasa promedio ponderada por saldo: el promedio simple miente cuando hay
  // una tarjeta chica al 30% junto a una hipoteca grande al 12%.
  const tasaPond = totalSaldo > 0
    ? items.reduce((s, d) => s + (d.ts || 0) * saldo(d), 0) / totalSaldo
    : 0;

  await build(buildFilename(t.deudas), (doc, autoTable) => {
    let y = chrome(doc, { titulo: t.deudas });

    y = resumen(doc, y, [
      { label: t.deudas, value: String(items.length) },
      { label: t.saldoTotal, value: fm(totalSaldo), color: [220, 38, 38] },
      { label: t.cuotaMensual, value: fm(totalCuota) },
      { label: t.tasaProm, value: pct(tasaPond) },
    ]);

    autoTable(doc, {
      ...tableStyle,
      startY: y,
      head: [[t.deuda, t.propietario, t.vinculada, t.saldo, t.cuotaMes, t.tasa, t.meses]],
      body: items
        .slice()
        .sort((a, b) => saldo(b) - saldo(a))
        .map((d) => {
          const meses = d.meses || d.n_cuotas || 0;
          return [
            d.n || d.nombre || "",
            ownerName(d.ownerId, owners),
            invName(d.invId),
            fm(saldo(d)),
            fm(cuota(d)),
            pct(d.ts || 0),
            meses > 0 ? String(meses) : "—",
          ];
        }),
      foot: [[t.total, "", "", fm(totalSaldo), fm(totalCuota), pct(tasaPond), ""]],
      columnStyles: {
        3: { halign: "right" }, 4: { halign: "right" },
        5: { halign: "right" }, 6: { halign: "right" },
      },
    });

    // Orden por tasa: es el orden en que conviene pagarlas (método avalancha).
    // La tabla de arriba va por saldo, que es lo que pesa; esta va por costo,
    // que es lo que decide cuál atacar primero.
    autoTable(doc, {
      ...tableStyle,
      startY: doc.lastAutoTable.finalY + 10,
      head: [[t.ordenPago, t.tasa, t.saldo, t.costoIntereses]],
      body: items
        .slice()
        .sort((a, b) => (b.ts || 0) - (a.ts || 0))
        .map((d) => [
          d.n || d.nombre || "",
          pct(d.ts || 0),
          fm(saldo(d)),
          fm(((d.ts || 0) / 100) * saldo(d)),
        ]),
      columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" } },
    });
  }, t.nota);
}
